# Generated by Django 4.0 on 2022-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkresult",
            name="is_accepted",
            field=models.BooleanField(
                default=False, help_text="Define if solution was correct"
            ),
        ),
    ]
