# Generated by Django 4.0 on 2022-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_homeworkresult_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='aproving_length',
            field=models.PositiveSmallIntegerField(
                default=5, help_text='min length of homework fot aproving'
                ),
        ),
    ]
