# Generated by Django 4.0 on 2022-01-12 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacher_aproving_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkresult',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='author', to='school.student'
                ),
        ),
    ]
